spring:
  application-name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5430/kart
    username: retailuser
    password: retailpass
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-test-query: SELECT 1
      pool-name: RetailHikariCp
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000       # 10 minutes
      max-lifetime: 1800000      # 30 minutes
      connection-timeout: 30000  # 30 seconds
      validation-timeout: 5000
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

  flyway:
    enabled: true
